set (MONGOC_ENABLE_CRYPTO_COMMON_CRYPTO 0)
set (MONGOC_ENABLE_CRYPTO_LIBCRYPTO 0)
set (MONGOC_ENABLE_CRYPTO_CNG 0)

IF(APPLE)
	MESSAGE(STATUS "Using OpenSSL")
	set (MONGOC_ENABLE_CRYPTO_LIBCRYPTO 1)
    set(MONGO_CRYPTO_LIBS "$ENV{OPENSSL_PATH}"/lib/libcrypto.1.0.0.dylib "$ENV{OPENSSL_PATH}"/lib/libssl.1.0.0.dylib)
    include_directories("$ENV{OPENSSL_PATH}"/include)
    MESSAGE(STATUS "OpenSSL include path: $ENV{OPENSSL_PATH}")
	MESSAGE(STATUS "Using Common Crypto for mongoc crypto")
ELSEIF(WIN32)
    MESSAGE(STATUS "Using CNG for mongoc crypto")
    set (MONGOC_ENABLE_CRYPTO_CNG 1)
    set(MONGO_CRYPTO_LIBS crypt32.lib Bcrypt.lib)
ELSE()
    MESSAGE(STATUS "Using OpenSSL for mongoc crypto")
    set (MONGOC_ENABLE_CRYPTO_LIBCRYPTO 1)
    include(FindOpenSSL)
    if (OPENSSL_FOUND)
        set(MONGO_CRYPTO_LIBS ${OPENSSL_LIBRARIES})
        include_directories(${OPENSSL_INCLUDE_DIR})
        MESSAGE(STATUS "Found OpenSSL libraries")
        MESSAGE(STATUS "OpenSSL include path: ${OPENSSL_INCLUDE_DIR}")
    else()
        MESSAGE(FATAL_ERROR "Could not find OpenSSL libraries")
    endif()
ENDIF()

MESSAGE(STATUS "using mongoc crypto library: ${MONGO_CRYPTO_LIBS}")
